name: SonarQube Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better SonarQube analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # Simple cache without path restrictions

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            spring-petclinic/target
          key: maven-${{ hashFiles('spring-petclinic/pom.xml') }}
          restore-keys: |
            maven-

      - name: Navigate to project and set permissions
        working-directory: ./spring-petclinic
        run: |
          pwd
          ls -la
          chmod +x mvnw

      - name: Run tests with Maven
        working-directory: ./spring-petclinic
        run: ./mvnw clean test -B

      - name: SonarQube Scan
        working-directory: ./spring-petclinic
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw -B verify sonar:sonar \
            -Dsonar.projectKey=sonarqube-java-ci-cd \
            -Dsonar.projectName="SonarQube Java CI/CD Demo" \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.sourceEncoding=UTF-8

      - name: Build JAR file
        working-directory: ./spring-petclinic
        run: ./mvnw -B package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-petclinic-jar
          path: spring-petclinic/target/*.jar
          retention-days: 1

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch pushes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: spring-petclinic-jar
          path: artifacts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no artifacts/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
          
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Install Java if not present
            if ! command -v java &> /dev/null; then
              sudo apt update && sudo apt install -y openjdk-17-jre
            fi
            
            # Stop existing application
            sudo pkill -f "java.*spring-petclinic" || true
            sleep 2
            
            # Start new application
            nohup java -jar /home/ubuntu/spring-petclinic-*.jar \
              --server.port=8080 \
              > /home/ubuntu/app.log 2>&1 &
            
            echo "Application deployed successfully"
          EOF
